[
    { id: 1, name: "Australia" },
    { id: 2, name: "Austria" },
    { id: 3, name: "Azerbaiyán" },
    { id: 4, name: "Anguilla" },
    { id: 5, name: "Argentina" },
    { id: 6, name: "Armenia" },
    { id: 7, name: "Bielorrusia" },
    { id: 8, name: "Belice" },
    { id: 9, name: "Bélgica" },
    { id: 10, name: "Bermudas" },
    { id: 11, name: "Bulgaria" },
    { id: 12, name: "Brasil" },
    { id: 13, name: "Reino Unido" },
    { id: 14, name: "Hungría" },
    { id: 15, name: "Vietnam" },
    { id: 16, name: "Haiti" },
    { id: 17, name: "Guadalupe" },
    { id: 18, name: "Alemania" },
    { id: 19, name: "Países Bajos, Holanda" },
    { id: 20, name: "Grecia" },
    { id: 21, name: "Georgia" },
    { id: 22, name: "Dinamarca" },
    { id: 23, name: "Egipto" },
    { id: 24, name: "Israel" },
    { id: 25, name: "India" },
    { id: 26, name: "Irán" },
    { id: 27, name: "Irlanda" },
    { id: 28, name: "España" },
    { id: 29, name: "Italia" },
    { id: 30, name: "Kazajstán" },
    { id: 31, name: "Camerún" },
    { id: 32, name: "Canadá" },
    { id: 33, name: "Chipre" },
    { id: 34, name: "Kirguistán" },
    { id: 35, name: "China" },
    { id: 36, name: "Costa Rica" },
    { id: 37, name: "Kuwait" },
    { id: 38, name: "Letonia" },
    { id: 39, name: "Libia" },
    { id: 40, name: "Lituania" },
    { id: 41, name: "Luxemburgo" },
    { id: 42, name: "México" },
    { id: 43, name: "Moldavia" },
    { id: 44, name: "Mónaco" },
    { id: 45, name: "Nueva Zelanda" },
    { id: 46, name: "Noruega" },
    { id: 47, name: "Polonia" },
    { id: 48, name: "Portugal" },
    { id: 49, name: "Reunión" },
    { id: 50, name: "Rusia" },
];
