export const countries = [
    {
        id: 1,
        name: "Venezuela",
        tlf: "58",
    },
    {
        id: 2,
        name: "Estados Unidos",
        tlf: "1",
    },
    {
        id: 3,
        name: "Argentina",
        tlf: "54",
    },
    {
        id: 4,
        name: "Colombia",
        tlf: "57",
    },
    {
        id: 5,
        name: "España",
        tlf: "34",
    },
    {
        id: 6,
        name: "México",
        tlf: "52",
    },
    {
        id: 7,
        name: "Ecuador",
        tlf: "593",
    },
];

export const states = {
    'Venezuela': [
        "Amazonas",
        "Anzoátegui",
        "Apure",
        "Aragua",
        "Barinas",
        "Bolívar",
        "Carabobo",
        "Cojedes",
        "Delta Amacuro",
        "Distrito Capital",
        "Falcón",
        "Guárico",
        "Lara",
        "Mérida",
        "Miranda",
        "Monagas",
        "Nueva Esparta",
        "Portuguesa",
        "Sucre",
        "Táchira",
        "Trujillo",
        "Vargas",
        "Yaracuy",
        "Zulia",
    ],
    'Estados Unidos': [
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Carolina del Norte",
        "Carolina del Sur",
        "Colorado",
        "Connecticut",
        "Dakota del Norte",
        "Dakota del Sur",
        "Delaware",
        "Florida",
        "Georgia",
        "Hawái",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Míchigan",
        "Minnesota",
        "Misisipi",
        "Misuri",
        "Montana",
        "Nebraska",
        "Nevada",
        "Nueva Hampshire",
        "Nueva Jersey",
        "Nueva York",
        "Nuevo México",
        "Ohio",
        "Oklahoma",
        "Oregón",
        "Pensilvania",
        "Rhode Island",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Virginia Occidental",
        "Washington",
        "Wisconsin",
        "Wyoming",
    ],
    'Argentina': [
        "Buenos Aires",
        "Catamarca",
        "Chaco",
        "Chubut",
        "Córdoba",
        "Corrientes",
        "Entre Ríos",
        "Formosa",
        "Jujuy",
        "La Pampa",
        "La Rioja",
        "Mendoza",
        "Misiones",
        "Neuquén",
    ],
    'Colombia': [
        "Amazonas",
        "Antioquia",
        "Arauca",
        "Atlántico",
        "Bolívar",
        "Boyacá",
        "Caldas",
        "Caquetá",
        "Casanare",
        "Cauca",
        "Cesar",
        "Chocó",
        "Córdoba",
        "Cundinamarca",
        "Guainía",
        "Guaviare",
        "Huila",
        "La Guajira",
        "Magdalena",
        "Meta",
        "Nariño",
        "Norte de Santander",
        "Putumayo",
        "Quindío",
        "Risaralda",
        "San Andrés y Providencia",
        "Santander",
        "Sucre",
        "Tolima",
        "Valle del Cauca",
        "Vaupés",
        "Vichada",
    ],
    'España': [
        "Almería",
        "Cádiz",
        "Córdoba",
        "Granada",
        "Huelva",
        "Jaén",
        "Málaga",
        "Sevilla",
        "Huesca",
        "Teruel",
        "Zaragoza",
        "Las Palmas",
        "Santa Cruz de Tenerife",
        "Albacete",
        "Ciudad Real",
        "Cuenca",
        "Toledo",
        "León",
        "Palencia",
        "Salamanca",
        "Segovia",
        "Soria",
        "Barcelona",
        "Girona",
        "Lleida",
        "Tarragona",
        "Alicante",
        "Valencia",
        "Badajoz",
        "Cáceres",
        "La Coruña",
        "Lugo",
        "Ourense",
        "Pontevedra",
        "Madrid",
    ],
    'México': [
        "Aguascalientes",
        "Baja California",
        "Baja California Sur",
        "Campeche",
        "Chiapas",
        "Chihuahua",
        "Coahuila",
        "Colima",
        "Durango",
        "Guanajuato",
        "Guerrero",
        "Hidalgo",
        "Jalisco",
        "México",
        "Michoacán",
        "Morelos",
        "Nayarit",
        "Nuevo León",
        "Oaxaca",
        "Puebla",
        "Querétaro",
        "Quintana Roo",
        "San Luis Potosí",
        "Sinaloa",
        "Sonora",
    ],
    'Ecuador': [
        "Azuay",
        "Bolívar",
        "Cañar",
        "Carchi",
        "Chimborazo",
        "Cotopaxi",
        "El Oro",
        "Esmeraldas",
        "Galápagos",
        "Guayas",
        "Imbabura",
        "Loja",
        "Los Ríos",
        "Manabí",
        "Morona-Santiago",
        "Napo",
        "Orellana",
        "Pastaza",
        "Pichincha",
        "Santa Elena",
        "Santo Domingo de los Tsáchilas",
        "Sucumbíos",
        "Tungurahua",
    ],
};
